encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry_name>", views.entry, name="entry"),
    path("search_results", views.search_results, name="search_results"),
    path("new", views.new, name="new"),
    path("edit/<str:entry_title>", views.edit, name="edit"),
    path("random", views.random_page, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django import forms
import markdown2
import random

from . import util



def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry_name):
    entry_content = util.get_entry(entry_name)
 
    if entry_content is None:
        return render(request, "encyclopedia/entry.html", {
            "entry_content": "Page Not Found",
            "entry_title": "Not Found"
        })
    else: 
        return render(request, "encyclopedia/entry.html", {
            "entry_content": markdown2.markdown(entry_content),
            "entry_title": entry_name
        })

def search_results(request):
    query = request.POST['q'] #working now for exact typing. Need to check for capitalized
    possible_entries = []                   
    entries = util.list_entries()
    for entry in entries:
        
        if entry.lower() == query.lower():
            return redirect('wiki:entry', entry_name=entry)
        elif query.lower() in entry.lower():
            possible_entries.append(entry)

    
    
    return render(request, "encyclopedia/search_results.html", {
        "possible_entries": possible_entries
    })
    

class NewEntryForm(forms.Form):
    title = forms.CharField(label = 'Title')
    content = forms.CharField(widget=forms.Textarea())


def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            if title in util.list_entries():
                error = "An entry with this title already exists!"
                return render(request, "encyclopedia/new.html", {
                    "error": error,
                    "form": NewEntryForm()
                })
            else: 
                util.save_entry(title, content)
                return redirect("wiki:entry", entry_name=title)

    else: 
        return render(request, "encyclopedia/new.html", {
            "form": NewEntryForm()
    })


class EditForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea())
    
def edit(request, entry_title):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            util.save_entry(entry_title, content)
            return redirect('wiki:entry', entry_name=entry_title)
    else:
        content = util.get_entry(entry_title)
        form = EditForm({'content': content})
        return render(request, "encyclopedia/edit.html", {
            "entry_title": entry_title,
            "form": form
        })

def random_page(request):
    entries = util.list_entries()
    entry_name = random.choice(entries)
    return redirect('wiki:entry', entry_name)

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_title }}
{% endblock %}

{% block body %}

    <h1>Edit Entry</h1>
    <form class="form" action="{% url 'wiki:edit' entry_title %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="submit-button" type="submit"> 
{% endblock %} 

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_title }}
{% endblock %}

{% block body %}
    
    {{ entry_content|safe }}
    {% if entry_content != 'Page Not Found' %}
        <a href="{% url 'wiki:edit' entry_title %}">Edit</a>
    {% endif %}
    
{% endblock %} 

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry %}" >{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search_results' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %} 

{% block body %} 
    <h1>Create a New Entry</h1>
        <span>{{ error }}</span>
        <form class="form" action="{% url 'wiki:new' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input class="submit-button" type="submit">    
    
    
   
{% endblock %} 

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>Search Results</h1>
        <ul>
            {% for entry in possible_entries %}
                <li><a href="{% url 'wiki:entry' entry %}" >{{ entry }}</a></li>
            {% endfor %} 
        </ul>
{% endblock %} 